// Source-abbreviation key. Names sourced from the 5etools / ttrpg-convert-cli source map.
export const SOURCE_NAMES: Record<string, string> = {
  "AAG": "Astral Adventurer's Guide",
  "ABH": "Astarion's Book of Hungers",
  "AI": "Acquisitions Incorporated",
  "AU": "Arcana Unleashed",
  "AUD": "Arcana Unleashed: Deadfall",
  "AWM": "Adventure with Muk",
  "AZfyT": "A Zib for your Thoughts",
  "AitFR-AVT": "Adventures in the Forgotten Realms: A Verdant Tomb",
  "AitFR-THP": "Adventures in the Forgotten Realms: The Hidden Page",
  "BAM": "Boo's Astral Menagerie",
  "BGDIA": "Baldur's Gate: Descent Into Avernus",
  "BGG": "Bigby Presents: Glory of the Giants",
  "BMT": "The Book of Many Things",
  "CM": "Candlekeep Mysteries",
  "CRCotN": "Critical Role: Call of the Netherdeep",
  "CoA": "Chains of Asmodeus",
  "CoS": "Curse of Strahd",
  "DC": "Divine Contention",
  "DMG": "Dungeon Master's Guide",
  "DSotDQ": "Dragonlance: Shadow of the Dragon Queen",
  "DitLCoT": "Descent into the Lost Caverns of Tsojcanth",
  "EEPC": "Elemental Evil Player's Companion",
  "EET": "Elemental Evil: Trinkets",
  "EFA": "Eberron: Forge of the Artificer",
  "EGW": "Explorer's Guide to Wildemount",
  "ERLW": "Eberron: Rising from the Last War",
  "FRAiF": "Forgotten Realms: Adventures in Faerûn",
  "FRHoF": "Forgotten Realms: Heroes of Faerûn",
  "FTD": "Fizban's Treasury of Dragons",
  "FToD": "Fizban's Treasury of Dragons",
  "GGR": "Guildmasters' Guide to Ravnica",
  "GoS": "Ghosts of Saltmarsh",
  "HAT-LMI": "Honor Among Thieves: Legendary Magic Items",
  "HB": "Homebrew / SRD Wiki",
  "HftT": "Hunt for the Thessalhydra",
  "HotB": "Heroes of the Borderlands",
  "HotDQ": "Hoard of the Dragon Queen",
  "IDRotF": "Icewind Dale: Rime of the Frostmaiden",
  "IMR": "Infernal Machine Rebuild",
  "JttRC": "Journeys through the Radiant Citadel",
  "KftGV": "Keys from the Golden Vault",
  "LFL": "Lorwyn: First Light",
  "LLK": "Lost Laboratory of Kwalish",
  "LMoP": "Lost Mine of Phandelver",
  "LR": "Locathah Rising",
  "LoX": "Light of Xaryxis",
  "MCV2DC": "Monstrous Compendium Volume 2: Dragonlance Creatures",
  "MM": "Monster Manual",
  "MOT": "Mythic Odysseys of Theros",
  "MOoT": "Mythic Odysseys of Theros",
  "MPMM": "Mordenkainen Presents: Monsters of the Multiverse",
  "MTF": "Mordenkainen's Tome of Foes",
  "NF": "Netheril's Fall",
  "NRH-AT": "NERDS Restoring Harmony: Adventure Together",
  "NRH-TLT": "NERDS Restoring Harmony: The Lost Tomb",
  "OGA": "One Grung Above",
  "OotA": "Out of the Abyss",
  "PHB": "Player's Handbook",
  "PSA": "Plane Shift: Amonkhet",
  "PSD": "Plane Shift: Dominaria",
  "PSI": "Plane Shift: Innistrad",
  "PSK": "Plane Shift: Kaladesh",
  "PSX": "Plane Shift: Ixalan",
  "PSZ": "Plane Shift: Zendikar",
  "PaBTSO": "Phandelver and Below: The Shattered Obelisk",
  "PotA": "Princes of the Apocalypse",
  "QftIS": "Quests from the Infinite Staircase",
  "RHW": "Ravenloft: The Horrors Within",
  "RMBRE": "The Lost Dungeon of Rickedness: Big Rick Energy",
  "RoT": "The Rise of Tiamat",
  "RoTOS": "The Rise of Tiamat Online Supplement",
  "SCAG": "Sword Coast Adventurer's Guide",
  "SCC": "Strixhaven: A Curriculum of Chaos",
  "SDW": "Sleeping Dragon's Wake",
  "SKT": "Storm King's Thunder",
  "SaCoC": "Strixhaven: A Curriculum of Chaos",
  "SatO": "Sigil and the Outlands",
  "TBoMT": "The Book of Many Things",
  "TCE": "Tasha's Cauldron of Everything",
  "TTP": "The Tortle Package",
  "TftD": "Tyranny of Dragons",
  "TftYP": "Tales from the Yawning Portal",
  "ToA": "Tomb of Annihilation",
  "UtHftLH": "Uni and the Hunt for the Lost Horn",
  "VEoR": "Vecna: Eve of Ruin",
  "VGM": "Volo's Guide to Monsters",
  "VRGR": "Van Richten's Guide to Ravenloft",
  "WBtW": "The Wild Beyond the Witchlight",
  "WDH": "Waterdeep: Dragon Heist",
  "WDMM": "Waterdeep: Dungeon of the Mad Mage",
  "WttHC": "Stranger Things: Welcome to the Hellfire Club",
  "XDMG": "Dungeon Master's Guide (2024)",
  "XGE": "Xanathar's Guide to Everything",
  "XMM": "Monster Manual (2024)",
  "XMtS": "X Marks the Spot",
  "XPHB": "Player's Handbook (2024)",
};

export function sourceName(code: string): string {
  return SOURCE_NAMES[code] || code;
}
